import { videoData } from "interface/types";

const CONST_VIDEO_DATA:videoData[]=[{
    id:1,
    videoURL:'/assets/amazon.mp4',
    imgSRC:'/assets/amazon.webp',
    autoplay:false,
},
{
    id:2,
    videoURL:'/assets/boats.mp4',
    imgSRC:'/assets/boats.jpeg',
    autoplay:false
},
{
    id:3,
    videoURL:'/assets/buildings.mp4',
    imgSRC:'/assets/buildings.jpeg',
    autoplay:false
},
{
    id:4,
    videoURL:'/assets/canada.mp4',
    imgSRC:'/assets/canada.jpeg',
    autoplay:false
},
{
 id:5,
 videoURL:'/assets/clouds_above_home.mp4',
 imgSRC:'/assets/clouds_above_home.jpeg',
 autoplay:false

},
{
id:6,
videoURL:'/assets/drone.mp4',
imgSRC:'/assets/drone.webp',
autoplay:false
},
{
id:7,
videoURL:'/assets/greenary.mp4',
imgSRC:'/assets/greenary.jpeg',
autoplay:false
},
{
id:8,
videoURL:'/assets/island.mp4',
imgSRC:'/assets/island.jpeg',
autoplay:false
},
{
    id:9,
    videoURL:'/assets/oceans.mp4',
    imgSRC:'/assets/oceans.jpeg',
    autoplay:false
},
{
    id:10,
    videoURL:'/assets/pigeons.mp4',
    imgSRC:'/assets/pigeons.jpeg',
    autoplay:false
},
{
    id:11,
    videoURL:'/assets/sea_secenry.mp4',
    imgSRC:'/assets/sea_secenry.jpeg',
    autoplay:false
},{
    id:12,
    videoURL:'/assets/video_1.mp4',
    imgSRC:'/assets/video_1.jpeg',
    autoplay:false
}
]
export default CONST_VIDEO_DATA;